name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Infinity0077
          outputs: |
            ./output/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v4
        with:
          name: snake
          path: ./output/github-contribution-grid-snake.svg
